// Privacy Policy copy (Prompt 05, Task 1). Extracted VERBATIM from
// .superpowers/sdd/cg-prompt-05/source-privacy.md. Zero words written,
// edited, rephrased, condensed, expanded, or reordered. The ONLY changes
// from the source are the strips the task brief requires: the draft
// document's header block, the attorney-and-Gary review notes at the
// bottom of the draft, the placeholder line for the state warning chrome
// (the real chrome renders separately), and every inline reviewer
// instruction bracket addressed to counsel or to Gary (removed cleanly
// with its leading space so sentences end at their own period). Every
// other bracketed placeholder (effective date, OCM license number,
// privacy contact email, payment processor, retention period, the
// sample-destruction placeholder) is kept exactly as written; nothing is
// substituted or guessed. Do not edit this file without an explicit
// content-review pass against the source draft.

import type { LegalDoc } from './types';

export const privacy: LegalDoc = {
  title: 'Privacy Policy',
  metaDescription:
    'How CedarGrowth collects, uses, and protects visitor, account, purchase, and genetic information.',
  reviewPending: true,
  lastUpdated: '2026-07-28',
  intro: [
    { kind: 'p', text: 'Effective date: [DATE].' },
    {
      kind: 'p',
      text: 'CedarGrowth asks people for something unusual: a saliva sample and permission to read part of their genome. A policy is the least we owe in return. This explains what we collect, why, how long we keep it, and the control you keep over all of it.',
    },
  ],
  sections: [
    {
      heading: '1. Who we are',
      blocks: [
        {
          kind: 'p',
          text: 'This site is operated by CedarGrowth Organics Solutions LLC, a New York State licensed cannabis processor, license [OCM LICENSE NUMBER], at 998 Broadway, Buffalo, New York 14212. Contact for privacy matters: [PRIVACY EMAIL].',
        },
      ],
    },
    {
      heading: '2. Age verification',
      blocks: [
        {
          kind: 'p',
          text: 'New York law requires this site to verify that every visitor is 21 or older. When you verify, we store a verification flag on your device for [PERIOD], together with your consent to view cannabis-related material. We do not store your date of birth.',
        },
      ],
    },
    {
      heading: '3. What we collect from visitors',
      blocks: [
        {
          kind: 'list',
          items: [
            '**Site analytics.** Aggregated usage data such as pages viewed, approximate region, and device type, configured so that we do not build individual profiles. We run no advertising pixels on any page.',
            '**Dispensary locator.** A location you choose to share is used for that lookup and is not stored.',
            '**Batch lookup.** A batch number you enter is a product identifier, not information about you.',
            '**Forms.** Where you write to us or request wholesale or practitioner information, we hold what you send and the record of when you sent it.',
          ],
        },
      ],
    },
    {
      heading: '4. What we collect from account holders',
      blocks: [
        {
          kind: 'p',
          text: 'If you hold an account, we hold your email address, your credentials in hashed form, your kit registration records, your consent record, and anything you choose to write in your own private notes.',
        },
        {
          kind: 'p',
          text: '**Private notes are private by construction.** Reflections you record in the app are readable only by you. They are not readable from any administrative context, there is no owner override, and this is a property of how the system is built rather than a permission setting.',
        },
      ],
    },
    {
      heading: '5. What we collect from kit purchasers',
      blocks: [
        {
          kind: 'p',
          text: 'Your name, delivery address, email, order record, and the kit identifier linking the physical kit to your account. Payment is processed by [PAYMENT PROCESSOR] and we do not hold your card details.',
        },
      ],
    },
    {
      heading: '6. Genetic information',
      blocks: [
        {
          kind: 'p',
          text: 'This section governs everything derived from a sample you send us. Where it differs from anything else in this policy, this section controls. The full account, including the laboratory and the specific markers, is at `/dna/privacy`.',
        },
        {
          kind: 'p',
          text: '**6.1 What we analyze.** Only the specific genetic markers in the stated thirteen-trait panel, all related to cannabinoid metabolism and response. We do not analyze, report, or retain results concerning disease risk, carrier status, ancestry, or any trait outside that panel. We do not sequence your whole genome.',
        },
        {
          kind: 'p',
          text: '**6.2 The consent model.** Analysis begins only after you register your kit and consent. Consent is given separately for each purpose, never bundled, never pre-ticked, and each consent is separately and immediately revocable. The purposes are: performing your analysis, storing your results so you can return to them, and, only if you separately agree, sharing your results with a practitioner you name.',
        },
        {
          kind: 'p',
          text: '**6.3 What we never do.** We do not sell genetic information. We do not license it, trade it, or transfer it as a business asset. We do not use it for advertising or share it for cross-context behavioral advertising. We do not provide it to insurers, employers, or educational institutions. We do not provide it to law enforcement absent valid legal process that we are unable to resist, and where the law permits us to tell you, we will.',
        },
        {
          kind: 'p',
          text: '**6.4 The sample itself.** Your physical saliva sample is [DESTROYED AFTER ANALYSIS / RETAINED FOR PERIOD], and if retained, it is retained only with your separate consent and you can order its destruction at any time.',
        },
        {
          kind: 'p',
          text: '**6.5 Your control.** You can export your genetic data and your full profile in a portable format, at any time, yourself. You can delete your genetic data, your results, and your account, at any time, yourself, without contacting us and without being asked why. Deletion means deletion of the results and the derived profile, and instruction to the laboratory to destroy the sample where retained. Where a record must survive deletion for a legal obligation, we tell you which record and why.',
        },
        {
          kind: 'p',
          text: '**6.6 Sharing with a practitioner.** Only where you have named that practitioner and given specific consent. That consent is time-limited, visible to you, and revocable in one action. Revoking it stops future access; it cannot retrieve what was already seen.',
        },
        {
          kind: 'p',
          text: '**6.7 Genetic information about relatives.** Genetic information about you is also, in part, information about people related to you, who have not agreed to anything. We limit what we analyze to the stated panel partly for this reason, and we do not build family linkages or attempt to identify relatives across accounts.',
        },
        {
          kind: 'p',
          text: '**6.8 Security of genetic data.** Genetic results are stored separately from identifying information, encrypted at rest and in transit, with access restricted to the minimum number of people required to operate the service, every access logged and audited.',
        },
      ],
    },
    {
      heading: '7. What we do not collect',
      blocks: [
        {
          kind: 'p',
          text: 'We sell no cannabis products, so we hold no cannabis purchase records. We hold no government identification. We do not buy data about you from anyone. We do not track consumption, dosage, or frequency of use, and we do not build a consumption record from anything you tell us.',
        },
      ],
    },
    {
      heading: '8. How we use information',
      blocks: [
        {
          kind: 'p',
          text: 'To operate the site and the service, to fulfil kit orders, to perform and deliver analyses you asked for, to comply with New York cannabis law and our other legal obligations, to answer you when you write, and to understand in aggregate what is working. Nothing else.',
        },
      ],
    },
    {
      heading: '9. Sharing',
      blocks: [
        {
          kind: 'p',
          text: 'With service providers who help us operate: hosting, email delivery, payment processing, kit fulfillment, and the analyzing laboratory. Each is bound by contract to our instructions and to purposes we specify. With regulators and authorities where the law requires. Never sold. Never shared for advertising.',
        },
        {
          kind: 'p',
          text: 'The analyzing laboratory is named at `/dna/privacy`, because you should know who handles your sample before you send it.',
        },
      ],
    },
    {
      heading: '10. Retention',
      blocks: [
        {
          kind: 'p',
          text: 'Site analytics persist in aggregate. Form correspondence is kept while it is live and for [PERIOD] after. Account data is kept while your account exists. Genetic data and results are kept until you delete them or close your account, and are not retained for a fixed period against your wishes. Records we are legally required to keep are kept for the period required and no longer.',
        },
      ],
    },
    {
      heading: '11. Your rights',
      blocks: [
        {
          kind: 'p',
          text: 'Depending on where you live, you may have rights to access, correct, delete, or port your personal information, and to object to or restrict certain processing. Write to [PRIVACY EMAIL] and we will verify and respond within the period your law requires. We honor reasonable requests regardless of where you live.',
        },
        {
          kind: 'p',
          text: 'For genetic data specifically, export and deletion are self-serve. You should not have to ask us, and you do not.',
        },
      ],
    },
    {
      heading: '12. Security',
      blocks: [
        {
          kind: 'p',
          text: "Access controls, encryption in transit and at rest, least-privilege internal access, audit logging, and monitoring, consistent with the New York SHIELD Act's reasonable safeguards requirement and with the sensitivity of what we hold. If a breach affecting your information occurs, we will notify you as the law requires and as decency requires, whichever is sooner.",
        },
      ],
    },
    {
      heading: '13. Under 21',
      blocks: [
        {
          kind: 'p',
          text: 'This site and this service are for adults 21 and over. We do not knowingly collect information from anyone under 21 and we delete any such record on discovery. We do not sell or analyze kits for minors under any circumstances.',
        },
      ],
    },
    {
      heading: '14. Changes',
      blocks: [
        {
          kind: 'p',
          text: 'If this policy changes, the effective date changes with it, and material changes are noted plainly on this page. **Where a change affects genetic information, we will notify account holders directly and, where the change alters the purpose of processing, ask for consent again rather than assume it.**',
        },
      ],
    },
  ],
};
